# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Luke Withell
tagline:          ''
description:      ''
url:              https://lwithall.github.io
baseurl:          /

author:
  name:           'Luke Withell'
  url:            https://lwithall.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lwithall/lwithall.github.io
